# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vVwv89C_8rpponTKzQZ0BulaXbeZESPn
"""

import requests
import matplotlib.pyplot as plt
import time
import csv
from datetime import datetime

# --- API Configuration ---
COIN = 'bitcoin'
CURRENCY = 'usd'
URL = f"https://api.coingecko.com/api/v3/simple/price?ids={COIN}&vs_currencies={CURRENCY}"

# --- CSV Setup ---
CSV_FILE = 'bitcoin_price_log.csv'

# Create and write headers if file doesn't exist
with open(CSV_FILE, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['timestamp', 'price_usd'])

def fetch_bitcoin_price():
    try:
        response = requests.get(URL)
        if response.status_code ==cd 200:
            data = response.json()
            price = data[COIN][CURRENCY]
            return price
        else:
            print(f"Failed to fetch data: {response.status_code}")
            return None
    except Exception as e:
        print(f"Error fetching data: {e}")
        return None

# --- Live data collection ---
price_data = []
time_stamps = []
try:
    while True:  # Infinite loop for real-time collection
        price = fetch_bitcoin_price()
        current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        if price is not None:
            # Append to in-memory lists for plotting
            price_data.append(price)
            time_stamps.append(current_time)

            # Save to CSV in real time
            with open(CSV_FILE, mode='a', newline='') as file:
                writer = csv.writer(file)
                writer.writerow([current_time, price])

            print(f"[{current_time}] Bitcoin Price: ${price:.2f}")

        time.sleep(60)  # Fetch data every 60 seconds

except KeyboardInterrupt:
    print("\nStopped collecting data. Generating plot...")

    # --- Plotting the price trend ---
    plt.figure(figsize=(12, 6))
    plt.plot(time_stamps, price_data, marker='o', linestyle='-', color='b')
    plt.title(f'Real-Time Bitcoin Price in {CURRENCY.upper()}')
    plt.xlabel('Time')
    plt.xticks(rotation=45)
    plt.ylabel(f'Price ({CURRENCY.upper()})')
    plt.grid(True)
    plt.tight_layout()
    plt.show()